School-of-Company/Expo-Client

.github/workflows/node.js.yml
=> 🔀 깃허브 ci 제작

src/views/SMS/ui/SMS/index.tsx, src/views/main/ui/main/index.tsx, src/views/signIn/ui/signIn/index.tsx, src/views/signUp/ui/signUp/index.tsx, src/widgets/SMS/ui/SMSContainer/index.tsx, src/widgets/layout/ui/Header/index.tsx, src/widgets/signIn/ui/signIn/index.tsx
간단한 스타일 문제가 있었다.
- header 스타일 변경
- 페이지 컴포넌트 좌우 간격 설정
- header height -> padding
- page component -> x padding 16px
=> 🔀 간단한 스타일 개선 

package-lock.json, package.json, src/app/api/auth/signup/route.ts, src/app/api/auth/sms/route.ts, src/entities/signIn/ui/SignInForm/index.tsx, src/entities/signUp/model/checkSmsCode.ts, src/entities/signUp/model/sendSms.ts, src/entities/signUp/model/showError.ts, src/entities/signUp/model/signup.ts, src/entities/signUp/model/useTimer.ts, src/entities/signUp/ui/SignUpForm/index.tsx, src/shared/libs/apiClient.ts, src/shared/ui/Button/index.tsx, src/shared/ui/Input/index.tsx, src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
회원가입 페이지 로직 제작
- state form -> react hook form 
- sign up api
- fsd design pattern
=> 🔀 회원가입 페이지 로직 제작

src/app/api/auth/signin/route.ts, src/app/api/auth/tokenReissue/route.ts, src/entities/signIn/model/showError.ts, src/entities/signIn/model/signin.ts, src/entities/signIn/ui/SignInForm/index.tsx, src/shared/libs/apiClient.ts, src/shared/libs/getRefresh.ts
로그인 페이지 로직 제작
- useState form -> react hook form
- 로그인 api 연결
- 리프래쉬 토큰 로직 제작
리프래쉬 토큰 로직을 테스트할 수 없어서 추후 테스트 진행 + 로직 추가 & 수정 필요
=> 🔀 로그인 페이지 로직 제작

src/app/(pages)/expo-detail/[id]/page.tsx, src/views/expo-detail/ui/expo-detail/index.tsx, src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
박람회 디테일 페이지 통시 진행
csr로 통신 진행
추후 api route로 변경 필요
=> 🔀 박람회 디테일 페이지 통시 진행

src/app/api/auth/signin/route.ts, src/app/api/auth/sms/route.ts, src/app/api/expo/[expo_id]/route.ts, src/app/api/expo/route.ts, src/entities/signIn/api/signin.ts, src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx, src/widgets/main/ui/ExpoListContainer/index.tsx
서버 통신을 route api로 변경
expo list route api로 변경
expo detail route api로 변경
서버 통신을 route api로 변경
=> 🔀 route api로 변경

src/entities/main/ui/ExpoListItem/index.tsx
expo 리스트 이미지 변경
이미지를 고정적으로 변경
- 서버에서 null이 돌아와서 고정적으로 변경함 추후 서버에서 날라오는 이미지로 변경할 필요가 있음
=> 🐛expo 리스트 이미지 변경

src/entities/create-exhibition/ui/Modal/index.tsx, src/widgets/create-exhibition/model/exhibitionFormHandler.ts
맵 생성 버그 해결
x축 y축을 거꾸로 설정하여 지도가 안보이는 문제가 있었다.
=> 🐛 맵 생성 버그 해결

src/app/api/standard/program/[expo_id]/route.ts, src/app/api/training/program/[expo_id]/route.ts, src/entities/expo-detail/ui/ContentListText/index.tsx, src/entities/expo-detail/ui/ContentText/index.tsx, src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
박람회 연수 불러오기
- 참겨자 연수 불러오기
- 연수자 연수 불러오기
=> 🔀 박람회 연수 불러오기

src/app/(pages)/application/[id]/[type]/page.tsx, src/shared/ui/Modal/index.tsx, src/views/application/ui/application/index.tsx, src/views/expo-detail/ui/expo-detail/index.tsx, src/widgets/application/ui/ApplicationLayout/index.tsx, src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
박람회 신청 참가자/연수자 구분
박람회 신청 참가자/연수자 라우팅
=> 🔀 신청 폼 라우팅

src/entities/layout/Header/model/navigationItems.ts, src/entities/layout/Header/model/useNavigation.ts
관리자/유저 헤더 구분 필요
role 값에 따라 헤더 구분
=> 🔀 일반 유저 헤더 제작

src/entities/layout/Header/model/navigationItems.ts, src/entities/layout/Header/model/useNavigation.ts, src/shared/ui/Modal/index.tsx, src/widgets/application/model/applicationFormHandler.ts, src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
=> 🔀 모달 이동 수정

src/app/(pages)/expo-manage/[expo_id]/page.tsx, src/app/(pages)/program/[expo_id]/page.tsx, src/app/(pages)/program/detail/[program_id]/page.tsx, src/app/api/standard/[expo_id]/route.ts, src/app/api/training/[expo_id]/route.ts, src/entities/program/ui/ProgramNavigation/index.tsx, src/shared/model/footerActions.ts, src/shared/stores/useNavigationStore.ts, src/shared/ui/Table/TableFooter/index.tsx, src/shared/ui/Table/TableForm/index.tsx, src/views/expo-manage/ui/expo-manage/index.tsx, src/views/program-detail/index.tsx, src/views/program-detail/ui/ProgramDetail/index.tsx, src/views/program/ui/Program/index.tsx, src/widgets/expo-manage/ui/ExpoManageForm/index.tsx, src/widgets/program-detail/index.tsx, src/widgets/program-detail/ui/ProgramDetailForm/index.tsx, src/widgets/program/ui/ProgramForm/index.tsx
프로그램 상세 페이지 제작
- 프로그램 상세 페이지 디자인
- naviagation 로직 제작
- training route api 생성
- standard route api 생성
- params props type 변경
- zustand를 적용하여 상태에 따라 api가 통신되게 적용
=> 🔀 프로그램 상세 페이지 제작

src/app/loading.tsx, src/entities/layout/Header/model/navigationItems.ts, src/entities/main/ui/ExpoListItem/index.tsx, src/shared/model/footerActions.ts, src/widgets/admin/ui/AdminPageWrapper/index.tsx, src/widgets/create-exhibition/model/exhibitionFormHandler.ts, src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx, src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
간단한 디자인 변경
- 헤더 변경
- 로딩 페이지 추가
- table 조건에 따라 변화
- 추후 디자인 대로 적용 할 필요가 있다.
=> 🔀 간단한 디자인 변경

src/app/api/training/application/[trainingPro_id]/route.ts, src/entities/application/ui/TrainingRadioGroup/index.tsx
=> 🔀 프로그램 연수 신청 api 수정

src/widgets/application/ui/form/ApplicationForm/standard/index.tsx, src/widgets/application/ui/form/ApplicationForm/trainee/index.tsx
=> 🔀 신청폼 라우팅 진행

src/shared/model/printUtils.ts
Qr 코드 사이즈 변경
qr 코드 사이즈를 프린트 용지에 맞게 줄였다.
=> 🔀 Qr 코드 사이즈 변경

src/shared/types/program-detail/type.ts, src/shared/types/program/type.ts, src/widgets/program-detail/api/getProgramDetailData.ts, src/widgets/program-detail/model/useProgramDetailData.ts, src/widgets/program-detail/ui/ProgramDetailForm/index.tsx, src/widgets/program/api/getProgramData.ts, src/widgets/program/model/useProgramData.ts, src/widgets/program/ui/ProgramForm/index.tsx
프로그램 페이지 tanstack-query로 변경했습니다.
- 프로그램 페이지 tanstack-query로 변경
- 프로그램 디테일 페이지 tanstack-query로 변경
캐싱을 더욱 테스트할 필요가 있어보인다.
=> ♻️ 프로그램 페이지 tanstack-query로 변경

src/shared/types/expo-manage/type.ts, src/widgets/expo-manage/api/getExpoManageData.ts, src/widgets/expo-manage/model/category.ts, src/widgets/expo-manage/model/useExpoData.ts, src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
route api에서 tanstack query api로 변경
route api에서 tanstack query api로 변경하였다.
=> ♻️ route api에서 tanstack query api로 변경

src/shared/libs/TanstackProviders.tsx, src/widgets/application/ui/ApplicationLayout/index.tsx
=> 박람회 준비중 메시지 출력

next.config.mjs, src/shared/libs/redis/redis.ts
=> 레디스에 비밀번호 설정

next.config.mjs, src/shared/libs/redis/redis.ts
변경 사항을 배포 브랜치에 반영
변경 사항을 배포 브랜치에 반영
=> 변경 사항을 배포 브랜치에 반영

next.config.mjs, src/shared/libs/redis/redis.ts
변경 사항을 배포 브랜치에 반영합니다
변경 사항을 배포 브랜치에 반영합니다
=> 변경 사항을 배포 브랜치에 반영합니다

src/shared/libs/handler/token.ts, src/shared/libs/handler/tokenHandler.ts, src/shared/libs/redis/lock.server.ts, src/shared/libs/redis/redis.server.ts, src/shared/libs/redis/redis.ts
redis 파일을 빌드 과정에서 client에 포함되지 않게 적용
redis 파일을 빌드 과정에서 client에 포함되지 않게 적용
=> redis 파일을 빌드 과정에서 client에 포함되지 않게 적용
